default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shasha_development

test:
  <<: *default
  database: shasha_test

production:
  <<: *default
  database: shasha_production
  username: shasha
  password: <%= ENV["SHASHA_DATABASE_PASSWORD"] %>
